version: '3'

services:
  malcolm:
    build:
      context: .
      dockerfile: docker/Dockerfile.malcolm
    container_name: malcolm
    privileged: true
    networks:
      malcolm_net:
        ipv4_address: 172.19.0.2
    volumes:
      - ./project:/project

  source:
    build:
      context: .
      dockerfile: docker/Dockerfile.containers
    container_name: source
    privileged: true
    networks:
      malcolm_net:
        ipv4_address: 172.19.0.3

  target:
    build:
      context: .
      dockerfile: docker/Dockerfile.containers
    container_name: target
    privileged: true
    networks:
      malcolm_net:
        ipv4_address: 172.19.0.4

  dummy:
    build:
      context: .
      dockerfile: docker/Dockerfile.containers
    container_name: dummy
    privileged: true
    networks:
      malcolm_net:
        ipv4_address: 172.19.0.5

networks:
  malcolm_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/29
