FROM debian:latest

RUN apt-get update && \
    apt-get install -y build-essential nano valgrind iputils iputils-ping iproute2 tcpdump && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /project

CMD ["sleep", "infinity"]
